#!/bin/sh
eps=$(find -maxdepth 1 -name '*.nfo_')
echo "$eps" | sed -r 's/(.*odc\. )([0-9]+)(.*)/[\2] \1\2\3/' | sort -n -k 1.2
defepnum=$(echo "$eps" | sed -r 's/.*odc\. ([0-9]+).*/\1/' | sort -n | head -n1)
read -p "Episode number to unlock [$defepnum]:" epnum
test -n "$epnum" || epnum=$defepnum
find -maxdepth 1 -name "*odc. $epnum.nfo_" | grep -q . || { echo "ERROR: Episode $epnum not found."; exit 1; }
rename -v 's/nfo_/nfo/' *odc.\ $epnum.nfo_
